apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Конфигурация приложений 2.3 https</title>
    </head>
    <body>
        <h1>Nginx & Multitool & https</h1>
    </body>
    </html>