---
# Роль: просмотр подов и сервисов
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: devuser-role
rules:
  - apiGroups: [""] # core API
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch", "describe"]

---
# Связь роли и сервис-аккаунта
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devuser_rolebind
subjects:
  - kind: ServiceAccount
    name: devuser
    namespace: default
roleRef:
  kind: Role
  name: devuser-role
  apiGroup: rbac.authorization.k8s.io

---
# Сервис-аккаунт = пользователь
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devuser
  namespace: default