apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: check-service
        image: busybox
        command: 
          - sh
          - -c
          - |
            # Проверяем полное DNS-имя сервиса в namespace default
            until nslookup nginx-service.default.svc.cluster.local; do
              echo "Waiting for service..."
              sleep 2
            done
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80