apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: multitool
spec:
  selector:
    matchLabels:
      name: multitool
  template:
    metadata:
      labels:
        name: multitool
    spec:
      containers:
      - name: multitool
        image: praqma/network-multitool
        command: ['sh', '-c', 'while true; do ls /shared/*.log || echo "Файлы не наидены"; sleep 10; done']
        resources:
        volumeMounts:
        - name: shared
          mountPath: /shared
          readOnly: true
        env:
        - name: HTTP_PORT
          value: "8080"
      volumes:
        - name: shared
          hostPath:
            path: /var/log